### ISSUE TITLE
Not showing up on Synology

### ISSUE THREAD

**Issue by kotysoft** [gala132/nCoreCouchPotatoProvider#1]
Hi. I got this error on Synology NAS
(at restart debug log)

```
[  couchpotato.core.loader] Skip loading module plugin ncore: Traceback (most recent call last):
  File "/volume1/@appstore/couchpotatoserver-custom/var/CouchPotatoServer/couchpotato/core/loader.py", line 164, in loadModule
    return import_module(name)
  File "/usr/local/couchpotatoserver-custom/var/CouchPotatoServer/libs/importhelper/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/couchpotatoserver-custom/var/custom_plugins/ncore/__init__.py", line 6, in <module>
    from .main import nCore
  File "/usr/local/couchpotatoserver-custom/var/custom_plugins/ncore/main.py", line 12, in <module>
    import simplejson
ImportError: No module named simplejson
```

**Version** abfd9d08 (2015. 03. 23. 16:23:09)
**Directories** 
```
/usr/local/couchpotatoserver-custom/var/CouchPotatoServer
/usr/local/couchpotatoserver-custom/var
```

Előre és utólag is köszönöm !

**Comment by kotysoft** [comment]
It looks I found my problem on **SYNOLOGY** nas.

I replaced the line in **main.py**
```python
import simplejson
```

with
```python
import json
```

and for first look it appeared and looking good. Currently testing

Köszi :)

**Comment by kotysoft** [comment]
:(

Sajna mégsem segített rajta :(

```
04-02 00:22:18ERROR[   couchpotato.core.event] Error in event "provider.search.torrent.movie", that wasn't caught: Traceback (most recent call last):
  File "/volume1/@appstore/couchpotatoserver-custom/var/CouchPotatoServer/couchpotato/core/event.py", line 15, in runHandler
    return handler(*args, **kwargs)
  File "/volume1/@appstore/couchpotatoserver-custom/var/CouchPotatoServer/couchpotato/core/media/_base/providers/base.py", line 220, in search
    self._searchOnTitle(title, media, quality, results)
  File "/usr/local/couchpotatoserver-custom/var/custom_plugins/ncore/main.py", line 26, in _searchOnTitle
    data = simplejson.loads(simplejson.dumps(self.getJsonData(url)))
NameError: global name 'simplejson' is not defined
encoding=UTF-8 debug=False args=['--daemon', '--pid_file', '/usr/local/couchpotatoserver-custom/var/couchpotatoserver-custom.pid', '--config_file', '/usr/local/couchpotatoserver-custom/var/settings.conf'] app_dir=/usr/local/couchpotatoserver-custom/var/CouchPotatoServer data_dir=/usr/local/couchpotatoserver-custom/var desktop=None options=Namespace(config_file='/usr/local/couchpotatoserver-custom/var/settings.conf', console_log=False, daemon=True, data_dir=None, debug=False, pid_file='/usr/local/couchpotatoserver-custom/var/couchpotatoserver-custom.pid', quiet=False)
```

**Comment by kotysoft** [comment]
Partially solved by replacing `simplejson` with `json` in main.py

**Comment by gala132** [comment]
Yeah, forgot to mension in the README that there could be dependencies which are not defaultly installed. (for example simplejson)
Will update it.
