### ISSUE TITLE
Traceback Error / Only finds half of the movies

### ISSUE THREAD

**Issue by ecomdata** [gala132/nCoreCouchPotatoProvider#14]
Hello,

Eloszor is szeretnek koszonetet mondani a hasznos pluginert.

Sajnos a filmek felet talalja csak meg mostansag az ncoreon. pedig a megfelelo kategoriakban ott van a film ahol a szoftver keres. Traceback errort dob csak a logban.

> Search for Green Room in BR-Rip ignoring ETA^[[0m
10-03 11:11:01 INFO ^[[0m[hpotato.core.plugins.base] Opening url: get https://ncore.cc/torrents.php?kivalasztott_tipus=xvid_hun,hd_hun,sd_hun&mire=green+room&miben=name&tipus=kivalasztottak_kozott&submit.x=0&submit.y=0&submit=Ok&tags=&searchedfrompotato=true&jsons=true, data: []^[[0m
10-03 11:11:01 ERROR ^[[31m[edia._base.providers.base] Failed to parsing nCore: Traceback (most recent call last):
  File "/root/CouchPotatoServer/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
^[[0m
10-03 11:11:01 ERROR ^[[31m[                    ncore] Failed getting results from nCore: Traceback (most recent call last):
  File "/root/.couchpotato/custom_plugins/ncore/main.py", line 35, in doSearch
    log.info('Number of torrents found on nCore = ' + str(data['total_results']))
TypeError: list indices must be integers, not str
^[[0m
10-03 11:11:02 INFO ^[[0m[hpotato.core.plugins.base] Opening url: get https://ncore.cc/torrents.php?kivalasztott_tipus=xvid,hd,sd&mire=green+room&miben=name&tipus=kivalasztottak_kozott&submit.x=0&submit.y=0&submit=Ok&tags=&searchedfrompotato=true&jsons=true, data: []^[[0m
10-03 11:11:02 INFO ^[[0m[                    ncore] Number of torrents found on nCore = 4^[[0m
10-03 11:11:02 INFO ^[[0m[core.media.movie.searcher] Search for Green Room in 720p ignoring ETA^[[0m
10-03 11:11:02 ERROR ^[[31m[edia._base.providers.base] Failed to parsing nCore: Traceback (most recent call last):
  File "/root/CouchPotatoServer/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

>

**Comment by ecomdata** [comment]
Barmilyen informaciora szukseged lenne kerlek irj nyugodtan. Koszonom ha foglalkozol vele.

**Comment by hollov** [comment]
Hali,
Ha bemásolod a linket az error log-ból a böngészőbe, akkor látod, hogy nincs találat az ncore-on.
(https://ncore.cc/torrents.php?kivalasztott_tipus=xvid_hun,hd_hun,sd_hun&mire=green+room&miben=name&tipus=kivalasztottak_kozott&submit.x=0&submit.y=0&submit=Ok&tags=&searchedfrompotato=true&jsons=true)

Konkrétan azért nincs, mert "Green Room" csak angol nyelven van fent, te pedig leszűrted a keresést csak magyar találatokra ;)
