### ISSUE TITLE
'NameError: global name 'json' is not defined'

### ISSUE THREAD

**Issue by kotysoft** [gala132/nCoreCouchPotatoProvider#7]
Commit: 95ceffc67dcce39bafa5e2521a200ac818f1e944
CP version: 2.6.3
Updater: Desktop

```
04-29 19:52:14 INFO [0m[core.media.movie.searcher] Search for Dumb and Dumber To in 720p ignoring ETA[0m
04-29 19:52:14 ERROR [31m[   couchpotato.core.event] Error in event "provider.search.torrent.movie", that wasn't caught: Traceback (most recent call last):
  File "C:\Users\KOTY\AppData\Roaming\CouchPotato\application\CouchPotato-2.6.3.win32\couchpotato\core\event.py", line 15, in runHandler
  File "C:\Users\KOTY\AppData\Roaming\CouchPotato\application\CouchPotato-2.6.3.win32\couchpotato\core\media\_base\providers\base.py", line 215, in search
  File "C:\Users\KOTY\AppData\Roaming\CouchPotato\custom_plugins\ncore\main.py", line 25, in _searchOnTitle
NameError: global name 'json' is not defined
```
[Full log](http://pastebin.com/FvSX0Hqb)

Something went wrong in 729d39d1ee4b31bfa275e402ad8e6b64db516add
When I simply just replace all (3) "simplejson" with "json" (using simple text editor) in first version then merging with latest commit, then everything ok with it.

So the only difference is the `import json`

**Comment by gala132** [comment]
Fixed
